WindowManager:
    StartScreen:
    MainScreen:


#where the grapics is created
<StartScreen>:
    Label:
        pos: 0, -100
        text: "press to start"

    Button:
        size: root.size
        opacity: 0
        on_release:
            root.manager.transition.duration = '0'#fyfy
            app.root.current = "mainScreen"
            app.runApp()
    
        
<MainScreen>:
    name: "mainScreen"
    Button:
        size: 100,100
        size_hint: None, None
        